---
- name: setup vm with ssh & apache2
  hosts: webserver
  become: yes
  tasks:

    - name: Ensure SSH service is running and enabled
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 service is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy Hello World HTML file
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Hello</title></head>
          <body><h1>Hello World!</h1></body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'

